version: "3"

services:
  sqldb: 
    build: db/.
    ports: 
      - "1433:1433"
    env_file: 
      - db/sqlserver.env
      - db/sapassword.env
    environment:
      - DB_PASS=${DB_PASS}
    volumes:
      - sqlsystem:/var/opt/mssql/

volumes:
  sqlsystem:
