version: "3"

services:
  web:
    build: .
    depends_on:
      - sqldb
    restart: unless-stopped
    ports:
      - 3000:3000

  sqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    env_file:
      - db/sqlserver.env
      - db/sapassword.env
    volumes:
      - sqlsystem:/var/opt/mssql/

volumes:
  sqlsystem:
