version: "3"

services:
  sqldb: 
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports: 
      - "1433:1433"
    env_file: 
      - db/sqlserver.env
      - db/sapassword.env
    volumes:
      - sqlsystem:/var/opt/mssql/

volumes:
  sqlsystem:
