version: "3"

services:
  sqldb:
    build: db/.
    ports:
      - "1433:1433"
    env_file:
      - db/sqlserver.env
      - db/sapassword.env
    environment:
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
    volumes:
      - sqlsystem:/var/opt/mssql/

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3100:3000"
    environment:
      - JAVA_TIMEZONE=America/Whitehorse
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes: 
      - metabase-db:/metabase-data

volumes:
  sqlsystem:
  metabase-db:
